- CRM/Financeextras/Upgrader.php
- CRM/Financeextras/Upgrader/Base.php
- LICENSE.txt
- README.md
- financeextras.civix.php
- financeextras.php
- info.xml
This PR adds CiviCRM extension skeleton to the repository.
The repository was empty.
The repository contains CiviCRM extension skeleton 
Extension files were generated by using` civix generate:module` command.
> CIWEM-15: Add extension skeleton

- CRM/Financeextras/Hook/BuildForm/AdditionalPaymentButton.php
- financeextras.php
- templates/CRM/AdditionalPayment/Form/Payment/RefundButton.tpl
- tests/phpunit/Civi/Financeextras/Hook/BuildForm/AdditionalPaymentButtonTest.php
Add Refund submit button in contribution page
Added hook for AdditionalPayment Form to add javascript code to add Submit Refund button
> CIVIPLUS-769: Add submit refund button in contribution records

- CRM/Financeextras/Form/Payment/Refund.php
- CRM/Financeextras/Hook/BuildForm/AdditionalPaymentButton.php
- Civi/Financeextras/Payment/Refund.php
- README.md
- api/v3/PaymentProcessor/GetRefundedAmount.php
- css/custom-civicrm.css
- js/custom.js
- templates/CRM/AdditionalPayment/Form/Payment/RefundButton.tpl
- templates/CRM/Financeextras/Form/Payment/Refund.tpl
- xml/Menu/financeextras.xml
Credit card refund functionality
1. Add refund payment functionality for any payment processor.
2. After click on submit credit card refund button you will see the refund payment screen.
There is no available amount 
We have added new api to get refund balance to calculate available amount to refund
Currently only "Stripe Extension" supports refunded amount API. So, other payment processor only shows original amount as available amount.
Added new action / api in Payment Processor to work as proxy to fetch Refunded / Remaining Transaction Amount ( Charged/Collected Amount - Partial Refunded amount(s) ) from Payment Processor using Payment Processors -> getRefundedAmountByChargeId() method
This API action need Transaction ID (`trxn_id`)  from Transaction ( `civicrm_financial_trxn` ) as …
> CIVIPLUS-776: Create credit card refunds

- xml/Menu/financeextras.xml
Fix Permission issue
Update Permission from "make online contribution" to "edit contributions"
Now it will display a button only if it's allowed.
> CIVIPLUSIB-1012: Fix Permission Issue in Menu

- templates/CRM/Financeextras/Form/Payment/Refund.tpl
There is an information message in the Refund form, as per the design info icon was missing.
The info icon was not added before the information message.
The info icon was added before the information message.
> CIVIPLUS-1030: Add Info Icon for information message in Refund form

- templates/CRM/Financeextras/Form/Payment/Refund.tpl
Payment Row Selection is Required. But The Validation message is not displayed properly. 
Payment Row Error is not displayed properly. 
Payment Row Error display and highlight properly if not selected. 
It was not displaying the title as there is no label for those inputs( radios ).
So, added the id and label "for" relation to get the proper title for errors.
> CIVIPLUS-1033: Fix validation error for Required Payment row

- templates/CRM/Financeextras/Form/Payment/Refund.tpl
In the Refund Form, User Need to select Payment Row if there are multiple Payment Rows/Transactions.
Users can select Already Refund Transaction (Even if it will be an error from the server side). but possible to choose on the frontend side. 
Make Payment Row selection Radio button disable if there is no available amount to refund.
> CIVIPLUS-1031: Disable already refunded Payment Row

- CRM/Financeextras/Form/Payment/Refund.php
- Civi/Financeextras/Payment/Refund.php
This PR fixes an error when trying to record a refund with a contribution's payment transactions have both online and offline payments.  i.e. one with Stripe and one with cash. 
The PR also includes the code improvement that avoid unexpected error and increase readability. 
[screencast-dev.localhost_8020-2023.04.14-10_21_45.webm](https://user-images.githubusercontent.com/208713/232015358-9ae65c69-18bb-4a77-bf87-b2075a937551.webm)
> CIVIPLUS-1272: Ignore offline transaction

- CRM/Financeextras/Form/Payment/Refund.php
This PR changes the error message when use is trying to refund amount more than refundable amount.
> CIVIPLUS-1273: Enhance error message

- CRM/Financeextras/Hook/PageRun/ContributionPageTab.php
- CRM/Financeextras/Hook/PageRun/PageRunInterface.php
- financeextras.php
- info.xml
- js/creditnote.js
- mixin/menu-xml@1.0.0.mixin.php
- templates/CRM/Financeextras/Page/Contribute/CreditNoteTab.tpl
- xml/Menu/financeextras.xml
This PR includes the following changes
- Adds a new tab called `Credit Notes` to the contact contribution view.
- Adds a new action link to the contribution list with the title `Add Credit Note`.
This new tab and action row link don't exist.
The tab called `Credit Notes` is now added to the contribution view and the contribution list now has a new action `Add Credit Note`.
The `Add Credit Note` action links to the new path `civicrm/contribution/creditnote` added in this PR.
> CIWEMB-289: Add tab and contribution row link for create credit note

- CRM/Financeextras/Upgrader.php
- Civi/Financeextras/Setup/Manage/AbstractManager.php
- Civi/Financeextras/Setup/Manage/CreditNoteAllocationTypeManager.php
- Civi/Financeextras/Setup/Manage/CreditNoteStatusManager.php
This pull request introduces changes related to the management of credit note status and allocation type option groups based on the extension lifecycle. It includes the addition of new classes and methods for managing these entities during installation, uninstallation, enabling, and disabling of the extension.
Previously, there was no dedicated management for credit note status and allocation type option groups.
With this pull request, the management of credit note status and allocation type option groups is implemented. and the option group and values will be added/removed/disabled/enabled based on the extension state.
- The `CreditNoteStatusManager` class is responsible for managing the credit note status option group and its associated option values. It provides methods to create, …
> CIWEMB-289: Add CreditNote allocation type and status option group

- CRM/Financeextras/BAO/CreditNote.php
- Civi/Api4/Action/CreditNote/ComputeTotalAction.php
- Civi/Api4/CreditNote.php
- Civi/Financeextras/Utils/CurrencyUtils.php
- ang/fe-creditnote/directives/creditnote-create.directive.html
- ang/fe-creditnote/directives/creditnote-create.directive.js
- ang/fe-creditnote/services/currency-codes.service.js
- tests/phpunit/Civi/Api4/Action/CreditNote/ComputeTotalActionTest.php
- tests/phpunit/Civi/Financeextras/Test/Helper/CreditNoteTrait.php
This pull request introduces the following changes as a sequel to this PR https://github.com/compucorp/io.compuco.financeextras/pull/28:
- Pass available currency to credit note view via a provider.
- Compute tax rates and total on total change when creating a credit note.
The credit note line items' total amount was not calculated in real-time.
The credit note line items' total amount is calculated in real-time.
An additional API endpoint action, named `ComputeTotalAction`, was introduced in the Credit Note entity. This action is designed to facilitate the recalculation of the total amount when a user makes changes that affect the overall amount. These changes can include modifying the quantity of a line item or selecting a different financial type.
The `ComputeTotalAction` requires an …
> CIWEMB-289: Show real time amounts updates when updating line items on credit note creating form

- CRM/Financeextras/BAO/CreditNote.php
- CRM/Financeextras/BAO/CreditNoteLine.php
- Civi/Api4/Action/CreditNote/CreditNoteSaveAction.php
- Civi/Financeextras/Utils/FinancialAccountUtils.php
- ang/fe-creditnote.ang.php
- ang/fe-creditnote/directives/creditnote-create.directive.js
- ang/fe-creditnote/services/credit-note-status.service.js
- tests/phpunit/Civi/Api4/Action/CreditNote/CreditNoteSaveActionTest.php
This pull request adds an endpoint to save a Credit Note. 
Before this pull request, there was no specific implementation for saving credit notes.
Credit notes are persisted to DB, and the expected financial accounting entries are credited.
A new Credit Note API action `CreditNoteSaveAction` is introduced in this PR for saving credit notes as a follow-up to this PR https://github.com/compucorp/io.compuco.financeextras/pull/28.
For accounting purposes when a new credit note is created,  the following financial accounting entries are also created :
- A Financial Transaction record for the Credit Note.
- A Entity Financial Transaction for the Credit Note Financial Transaction.
- A Financial Item entity record is created for each credit note line item (Without tax amount).
- A Entity …
> CIWEMB-289: Save Credit Note and create financial accounting entries

- Civi/Api4/Action/CreditNote/GetAction.php
- Civi/Api4/CreditNote.php
- tests/phpunit/Civi/Api4/Action/CreditNote/GetActionTest.php
This pull request adds functionality to return the credit note allocated and the remaining credit via API.
Currently, the Credit Note Get API does not provide information about the allocated and remaining credit for credit notes.
```php
[
{
"id": 2,
"contact_id": 2,
"cn_number": null,
"date": "2023-06-06",
"status_id": 1,
"reference": "Licom po...",
"currency": "GBP",
"description": "<p>Police Profile drut</p>",
"comment": "Police",
"subtotal": 408,
"sales_tax": 0,
"total_credit": 408,
}
]
```
With this pull request, the Credit Note Get API is enhanced to include the allocated and remaining credit for credit notes. 
```php
[
{
"id": 2,
"contact_id": 2,
"cn_number": null,
"date": "2023-06-06",
"status_id": 1,
"reference": "Licom po...",
"currency": "GBP",
"description": "<p>Police Profile …
```
> CIWEMB-286: Return credit note allocated and remaining credit via API

- ang/fe-creditnote/directives/creditnote-create.directive.js
- ang/fe-creditnote/directives/history-back.directive.js
- templates/CRM/Financeextras/Page/Contribute/CreditNoteTab.tpl
This PR redirects the user to the credit note allocation screen post-credit note creation.
The user was redirected to CiviCRM's main page after creating a credit note.
The user is redirected to the credit note allocation screen after creating a credit note.
The allocation screen will be created in this PR https://github.com/compucorp/io.compuco.financeextras/pull/37
> CIWEMB-333: Redirect to allocation screen on credit note creation

- ang/fe-creditnote/directives/history-back.directive.js
- info.xml
- managed/SavedSearch_Credit_Notes.mgd.php
In this PR we export the credit note saved search so it can be imported automatically on extension install/uninstall.
Kindly see this link for more information on managed entities:
https://docs.civicrm.org/dev/en/latest/api/v4/managed/
> CIWEMB-289: Export CreditNotes saved search

- CRM/Financeextras/Page/Contribute/CreditNoteAngular.php
- ang/fe-creditnote/directives/creditnote-create.directive.html
- ang/fe-creditnote/directives/creditnote-create.directive.js
- templates/CRM/Financeextras/Page/Contribute/CreditNoteAngular.tpl
This PR  makes the following updates to the credit note create screen.
The sales tax account name was used as tax label
The tax terms from contribution settings is used as tax label
Clicking on the cancel button attempts to take the user to the previous page but sometimes instead of the credit note tab loading, it displays the summary tab.
https://github.com/compucorp/io.compuco.financeextras/assets/85277674/7ecbd166-5833-4dca-8cf4-147c2f60251a
The contact field is not prefilled
> CIWEMB-367: Update to Credit note create screen

- Civi/Api4/CreditNote.php
- ang/fe-creditnote/directives/creditnote-allocation-table.directive.html
- ang/fe-creditnote/directives/creditnote-line-table.directive.html
- ang/fe-creditnote/directives/creditnote-view.directive.html
- ang/fe-creditnote/directives/creditnote-view.directive.js
- templates/CRM/Financeextras/Page/Contribute/CreditNoteAngular.tpl
- xml/Menu/financeextras.xml
This PR updates the credit note view screen
Previously, credit notes were shown using the create directive, but with the fields disabled. However, in this pull request (PR), we have introduced a new directive and path specifically for displaying credit notes.
> CIWEMB-370: Revamp the credit note view screen

- CRM/Financeextras/Form/Contribute/CreditNoteDownload.php
- CRM/Financeextras/Form/Contribute/CreditNoteEmail.php
- Civi/Financeextras/Event/CreditNoteDownloadedEvent.php
- Civi/Financeextras/Event/CreditNoteMailedEvent.php
- Civi/Financeextras/Event/Subscriber/CreditNoteInvoiceSubscriber.php
- financeextras.php
- managed/SavedSearch_Credit_Notes.mgd.php
- templates/CRM/Financeextras/Form/Contribute/CreditNoteEmail.tpl
- xml/Menu/financeextras.xml
This PR adds the functionality that allows the user to email a credit note invoice to contacts.
No functionality to send credit note invoice emails to contacts
The user can now send credit note invoice emails to contacts, and an activity is created with the mail recipients as target contact.
Additionally, as part of this email functionality, Two new types of invoice-related activity types are now created: "Emailed Invoice" and "Downloaded Invoice." The former is created when an invoice is sent to a contact via email, while the latter is generated when the invoice is downloaded in PDF format.
For both types of activities, we ensure that the credit note invoice is attached to the corresponding activity record.
> CIWEMB-304: User can email credit note invoice to contact

- CRM/Financeextras/Hook/Links/Contribution.php
- CRM/Financeextras/Page/Contribute/CreditNoteAngular.php
- Civi/Financeextras/APIWrapper/Contribution.php
- ang/fe-creditnote/directives/creditnote-create.directive.html
- ang/fe-creditnote/directives/creditnote-create.directive.js
- financeextras.php
- templates/CRM/Financeextras/Page/Contribute/CreditNoteAngular.tpl
This PR allows users to create a credit note for a contribution and populate the credit note line items from the contribution line item. 
Users can not open a new credit notes screen for a contribution with the line items populated.
Users can open a new credit notes screen for a contribution with the line items populated.
To populate the line items, we take the remaining amount to be paid on the invoice, which is the due amount(i.e. total - paid). Then, we distribute this amount proportionally among the line items based on their total amount.
The following rule is followed:
In cases where no payments or allocations have been made against the invoice (i.e. percentage due is equal to 100), a credit note line is created for each line item on the invoice, with the full amount allocated to …
> CIWEMB-306: User can open credit note screen with line items from contribution

- CRM/Financeextras/BAO/CreditNote.php
- CRM/Financeextras/BAO/CreditNoteLine.php
- CRM/Financeextras/Form/Contribute/CreditNoteVoid.php
- Civi/Api4/Action/CreditNote/VoidAction.php
- Civi/Api4/CreditNote.php
- Civi/Financeextras/Utils/OptionValueUtils.php
- js/creditnote.js
- managed/SavedSearch_Credit_Notes.mgd.php
- templates/CRM/Financeextras/Form/Contribute/CreditNoteVoid.tpl
- tests/phpunit/Civi/Api4/Action/CreditNote/VoidActionTest.php
- tests/phpunit/Civi/Financeextras/Test/Helper/CreditNoteTrait.php
- xml/Menu/financeextras.xml
This PR allows users to void a credit note
The functionality wasn't available
Users can void a credit note
[screencast-compu.test_8888-2023.07.05-13_32_50.webm](https://github.com/compucorp/io.compuco.financeextras/assets/85277674/1a619a39-9fd4-45bd-91b6-9ad381b198fb)
To void a credit note, its status is changed to `void`, and additional accounting entries are generated to reverse the effects of the credit note.
In a previous [PR](https://github.com/compucorp/io.compuco.financeextras/pull/30), when a credit note is generated, a set of financial accounting entries is created. In this PR, we replicate the same account accounting entries but with positive amounts instead of negative amounts, which is the case for new credit notes.
Furthermore, a credit note can only be voided if it does not …
> CIWEMB-294:User can void credit note

- CRM/Financeextras/BAO/CreditNote.php
- CRM/Financeextras/BAO/CreditNoteAllocation.php
- CRM/Financeextras/Form/Contribute/CreditNoteAllocate.php
- CRM/Financeextras/Form/Contribute/CreditNoteDelete.php
- Civi/Api4/Action/CreditNoteAllocation/AllocateAction.php
- Civi/Api4/CreditNoteAllocation.php
- financeextras.php
- templates/CRM/Financeextras/Form/Contribute/CreditNoteAllocate.tpl
- tests/phpunit/Civi/Api4/Action/CreditNoteAllocation/AllocateActionTest.php
- xml/Menu/financeextras.xml
This PR allows users to allocate credit from a credit note to an invoice.
There was no credit allocation function.
Users can now allocate credit to an invoice.
This PR introduced a new API endpoint `CreditNoteAllocation.Allocate`, which facilitates the allocation of credit to contributions. When credit is applied to a contribution, it requires the creation of accounting entries to accurately allocate the payment within CiviCRM. The newly introduced API endpoint takes care of this also.
To streamline the process of creating these accounting entries and avoid redundant work within the system, we have adopted the recommended approach by CiviCRM, as outlined in the documentation (https://docs.civicrm.org/dev/en/latest/financial/paymentAPI/). So, instead of manually generating accounting …
> CIWEMB-300: User can allocate credit notes to invoices

- CRM/Financeextras/Page/Contribute/CreditNoteAngular.php
- Civi/Api4/Action/CreditNote/CreditNoteSaveAction.php
- ang/fe-creditnote/directives/creditnote-allocation-table.directive.html
- ang/fe-creditnote/directives/creditnote-allocation-table.directive.js
- ang/fe-creditnote/directives/creditnote-create.directive.html
- ang/fe-creditnote/directives/creditnote-create.directive.js
- ang/fe-creditnote/directives/creditnote-line-table.directive.html
- ang/fe-creditnote/directives/creditnote-view.directive.html
- css/fe-creditnote.css
With this PR user can edit a credit note.
The user couldn't edit a credit note
The user can edit a credit note
Also, we've added a delete button to the credit note allocation list (Type invlice). The delete functionality will be added in a different PR
Presently because of the accounting complexities and implications only the following fields can be updated by a user
- date
- comment
- cn_number
- reference
- description
While other fields are displayed as read-only.
> CIWEMB-293: User can edit credit note

- managed/SavedSearch_Credit_Notes.mgd.php
This PR updates the icon used for the credit note list action menu items.
> CIWEMB-291: Update action menu items icon

- CRM/Financeextras/BAO/CreditNoteAllocation.php
- Civi/Api4/Action/CreditNoteAllocation/GetAction.php
- Civi/Api4/CreditNoteAllocation.php
- financeextras.php
This PR enhances the GET API for credit note allocation by including the `Debit account` of the associated financial transaction in the response.
The `CreditNoteAllocation.get` API response does not include the `paid_from` field.
```
[
{
"id": 1,
"credit_note_id": 1,
"contribution_id": 5598,
"type_id": 1,
"currency": "GBP",
"reference": "Predoli",
"amount": 10,
"date": "2023-07-13",
"is_reversed": false
}
]
```
The `CreditNoteAllocation.get` API response now includes the `paid_from` field.
```
[
{
"id": 1,
"credit_note_id": 1,
"contribution_id": 5598,
"type_id": 1,
"currency": "GBP",
"reference": "Predoli",
"amount": 10,
"date": "2023-07-13",
"is_reversed": false,
"paid_from": "Accounts Receivable"
}
]
```
When a credit note is allocated to an invoice, a new record is created in the …
> CIWEMB-365: Display Debit account Credit note allocation is linked to

- ang/fe-creditnote/directives/creditnote-allocation-table.directive.html
- ang/fe-creditnote/directives/creditnote-allocation-table.directive.js
- ang/fe-creditnote/directives/creditnote-create.directive.js
- ang/fe-creditnote/directives/creditnote-view.directive.html
- ang/fe-creditnote/directives/creditnote-view.directive.js
- ang/fe-creditnote/services/money-format.service.js
This PR enables the user to delete credit note allocation using the endpoint added in this [PR](https://github.com/compucorp/io.compuco.financeextras/pull/52)
The delete allocation button does not work
The allocation delete button now works
> CIWEMB-365: User can reverse credit note allocation from UI

- ang/fe-creditnote.ang.php
- ang/fe-creditnote/directives/creditnote-allocation-table.directive.js
- ang/fe-creditnote/directives/creditnote-view.directive.html
- ang/fe-creditnote/directives/creditnote-view.directive.js
- css/fe-creditnote.css
- js/strftime.js
This pull request aims to improve the credit note view screen by implementing the following changes:
- Displaying the tax term instead of the account tax name.
- Displaying the currency name instead of the currency symbol.
- Formatting the date using the short date format specified by the user in the Date localization settings (`admin/setting/date?action=reset=1`).
The previous version of the credit note view screen displayed the tax name instead of the tax term, and it showed the currency symbol instead of the currency name. Additionally, the date format was not customized according to the user's preferences.
The updated credit note view screen now reflects the following improvements:
- The tax term is displayed instead of the account tax name.
- The currency name is shown in place of …
> CIWEMB-370: UI update to credit note view screen

- Civi/Financeextras/Event/ContributionPaymentUpdatedEvent.php
- Civi/Financeextras/Event/Listener/ContributionPaymentUpdatedListener.php
- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- Civi/Financeextras/Hook/PostProcess/ContributionPostProcess.php
- Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php
- financeextras.php
- js/modifyContributionForm.js
- templates/CRM/Financeextras/Form/Contribute/AddPayment.tpl
This PR introduces changes to the contribution status handling and payment recording process. It removes the ability for users to manually set the status of a new contribution from the UI. Instead, the contribution status will be automatically updated based on the payment made to the contribution. Additionally, users have the option to record a payment for the new contribution.
Previously, users could set the contribution status from the UI.
With this update, users can no longer set the contribution status from the UI. However, they can record a payment for the new contribution if needed.
To handle the contribution status updates, a new event `fe.contribution.received_payment` is introduced. The contribution status will be updated based on the following conditions:
| Status           | …
> CIWEMB-316:  Update Contribution Status Based on Payment

- Civi/Financeextras/Hook/BuildForm/MembershipCreate.php
- Civi/Financeextras/Hook/ValidateForm/MembershipCreate.php
- financeextras.php
- js/modifyMemberForm.js
- templates/CRM/Financeextras/Form/Member/AddPayment.tpl
The change introduced in this PR makes the recording of payment for associated contributions during new membership registration for a contact optional. The contribution status field has also been removed from the user interface (UI).
Previously, users had the ability to change the membership contribution status from the UI, as the contribution was directly linked to the payment.
Now, users can use the `Record Payment` checkbox to decide whether to record a payment or not when creating a new membership registration.
When the checkbox is unchecked and no payment will be recorded, and the associated contribution will have no payment linked to it, resulting in a "pending" status.
Simultaneously, the membership registration itself will also have a "Pending" status.
The majority of the changes …
> CIWEMB-320: User can optionally record payment for new membership

- .github/workflows/tests.yml
- CRM/Financeextras/Form/Contribute/CreditNoteAllocate.php
- Civi/Api4/Action/CreditNoteAllocation/AllocateAction.php
- ang/fe-creditnote/directives/creditnote-create.directive.js
This PR ensures the allocation amount is always positive and doesn't exceed 2 decimal places.
The allocation amount field was not validated against negative and multiple DPs.
The allocation amount must be positive can not exceed 2 DPs.
> CIWEMB-419: Set allocation amount to 2DP

- CRM/Financeextras/Form/Contribute/CreditNoteEmail.php
- Civi/Financeextras/Event/CreditNoteMailedEvent.php
- Civi/Financeextras/Event/Subscriber/CreditNoteInvoiceSubscriber.php
- templates/CRM/Financeextras/Form/Contribute/CreditNoteEmail.tpl
This PR makes the following updates to the credit note email functionality
- Add token selector for subject and message body
- Updates the mail sent alert message to `Credit Note Sent by Email Successfully.`
- Include the mail body in the activity log.
Subject and token selectors can be seen
The activity log now includes the email body in its details.
> CIWEMB-422: Update CreditNote email functionality

- ang/fe-creditnote/directives/creditnote-create.directive.js
This pull request addresses an error that occurs when clicking the cancel button on the contribution credit note create page. The error is caused by the contact ID not being set. The solution is to set the page's contact ID state variable to the contribution contact.
https://github.com/compucorp/io.compuco.financeextras/assets/85277674/85435eb8-85b9-41bc-a9f6-dbe55e5e250f
> CIWEMB-414: Set contact Id from contribution

- Civi/Financeextras/Hook/BuildForm/ParticipantCreate.php
- Civi/Financeextras/Hook/PostProcess/ParticipantPostProcess.php
- financeextras.php
- js/modifyParticipantForm.js
- templates/CRM/Financeextras/Form/Event/AddContribution.tpl
This Pull Request (PR) introduces a change that grants users the flexibility to optionally record a contribution for new Event registrations. With this update, users can now register participants for paid events without requiring a contribution (Free Ticket). Alternatively, they can create a contribution and choose to record a payment for it (Paid Ticket).
Previously, the user interface did not visually differentiate between contributions and payments during event registration. As a result, users lacked the option to record a contribution without creating a payment for it.
With this update, users can now make the choice to record a contribution and optionally record a payment. The UI has been restructured to clearly separate contribution-related fields from payment-related fields, …
> CIWEMB-319: User can create contribution for event without payment

- Civi/Api4/Action/CreditNote/GetAction.php
- Civi/Api4/CreditNoteAllocation.php
- Civi/Financeextras/APIWrapper/SearchDisplayRun.php
This PR fixes the issue with the credit notes table using the system's default currency, instead of the credit note specified currency.
The Credit Note table now respects the credit note specified currency.
> CIWEMB-404: Format money columns with the creditnote currency

- Civi/Financeextras/Service/CreditNoteInvoiceService.php
- templates/CRM/Financeextras/MessageTemplate/CreditNoteInvoice.tpl
This PR updates the Credit Note PDF template, removing Currency where it is not needed, and using the right currency where it is needed
> CIWEMB-420: Ensure PDF display the right currency

- CRM/Financeextras/Form/Contribute/CreditNoteAllocate.php
- ang/fe-creditnote/directives/creditnote-create.directive.js
This PR introduces the following changes:
- The currency used is taken from the contribution when creating credit notes from contributions.
- The minimum amount for credit note allocation has been set to zero.
The contribution is in USD, but the credit note shows GBP(i.e. the default currency).
The contribution is in USD, and the credit note now shows USD as expected.
> CIWEMB-413: Ensure the Credit note currency is set to the appropriate value

- ang/fe-creditnote/directives/creditnote-allocation-table.directive.html
- ang/fe-creditnote/directives/creditnote-view.directive.js
This PR introduces the following changes to the credit note view screen:
- Uses the same button bg colour for the `Edit` and `Allocate` button
- Converts the credit note date string retrieved from the API into a JavaScript Date object before formatting. This ensures that the date is correctly formatted when passed to the `strftime` formatted function.
The credit note date is `25-08-2023` but shows as `08/07/2023` when formatted to `Month/Day/Year`.
The credit note date is `25-08-2023` and now shows as `08/25/2023` when formatted to `Month/Day/Year` as expected.
> CIWEMB-370: Update Credit note view screen

- CRM/Financeextras/Upgrader.php
- Civi/Financeextras/Event/Subscriber/CreditNoteInvoiceSubscriber.php
- Civi/Financeextras/Setup/Manage/CreditNoteActivityTypeManager.php
This pull request introduces new activity types, "Downloaded credit note" and "Emailed credit note", which will be used to track credit note download and email activity respectively.
The activity types 'Downloaded Invoice' and 'Emailed Invoice' were used when a credit note is downloaded or emailed.
The `Downloaded credit note` and `Emailed credit note` are now used when a credit note is downloaded or emailed.
> CIWEMB-422: Add creditnote email/download activity type

- Civi/Api4/Action/CreditNote/VoidAction.php
- Civi/Api4/CreditNoteLine.php
- Civi/Financeextras/Service/CreditNoteInvoiceService.php
- templates/CRM/Financeextras/Form/Contribute/CreditNoteEmail.tpl
- xml/Menu/financeextras.xml
Before this PR non-admin users(i.e. users without Administer CiviCRM role) couldn't perform some credit note-related actions such as `void`.
> CIWEMB-403: Allow non-admin users with appropriate permission to access Credit note action

- templates/CRM/Financeextras/Form/Contribute/AddPayment.tpl
[see title]
The check number field was not properly aligned.
The check number field is now properly aligned.
> CIWEMB-456: Align check number field

- financeextras.php
This PR adds support for CreditNote and Credit Note line entity to FinancialItem and Entity Financial Transaction entity API
The FinancialItem and Entity Financial Transaction Get API does not retrieve records where the entity_table is either CreditNote or CreditNoteLine.
The FinancialItem and Entity Financial Transaction Get API now retrieve records where the entity_table is either CreditNote or CreditNoteLine.
Similar PR here https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/404
> CIWEMB-290: Add support for CreditNote entity to Financial entities API

- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- js/modifyContributionForm.js
- templates/CRM/Financeextras/Form/Contribute/CustomLineItem.tpl
In this PR we open the line-item editor by default on the new contribution screen.
Users have to use the `add line-item(s)` button to open the line-item editor screen
The line-item editor screen is opened by default
The changes introduced in this pull request mostly involve UI updates to simplify the contributing total amounts display. Prior to this pull request, the new/edit contribution page allows the contribution total amount to be provided in three ways: Total Amount (single field), Add Line Items (one or more), and Price Sets.
With this PR the options are now limited to Add Line Items (one or more), and Price Sets.
> CIWEMB-423: Open a contribution with the line item editor by default

- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- Civi/Financeextras/Hook/BuildForm/ContributionView.php
- financeextras.php
- js/addContributionCreditNoteBtn.js
This pull request adds a "create new credit note" button next to the contribution status on the contribution view screen.
clicking on the button opens up the credit note create screen, with line items populated from the contribution.
> CIWEMB-431: Add Contribution Credit note create button

- financeextras.php
- js/modifyParticipantForm.js
- templates/CRM/Financeextras/Form/Event/AddContribution.tpl
This PR introduces the following changes
- Add currency symbol to payment amount label in the event registration screen
- Recalculate contribution status post-update
The currency symbol is not displayed beside the amount label
The currency symbol is displayed beside the amount label
In this [PR](https://github.com/compucorp/io.compuco.financeextras/pull/56) where we added a new event to recalculate contribution status, we mentioned that we would later locate a centralized location to emit the event.
In this PR we have decided to do this in the  [hook_civicrm_post](https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_post/).
> CIWEMB-457: Recalculate contribution status post-update

- CRM/Financeextras/BAO/CreditNote.php
- CRM/Financeextras/BAO/CreditNoteAllocation.php
- CRM/Financeextras/BAO/CreditNoteLine.php
- CRM/Financeextras/Form/Contribute/CreditNoteRefund.php
- Civi/Api4/Action/CreditNote/RefundAction.php
- Civi/Api4/CreditNote.php
- Civi/Financeextras/APIWrapper/SearchDisplayRun.php
- managed/SavedSearch_Credit_Notes.mgd.php
- templates/CRM/Financeextras/Form/Contribute/CreditNoteRefund.tpl
- tests/phpunit/Civi/Api4/Action/CreditNote/RefundActionTest.php
- xml/Menu/financeextras.xml
This PR adds the functionality that allows an admin user to record a cash refund for a credit note.
The functionality doesn't exist
When a credit note cash refund is made, the following records are created during the reversal process:
- financial_trxn: A record of the refund payment.
- entity_financial_trxn for credit note: Links the credit note with the financial_trxn.
- entity_financial_trxn for credit note line: Each credit note line item is linked to the financial transaction, and the refunded amount is proportionally distributed among the credit note line items.
> CIWEMB-295: Allow user to create credit note refund

- CRM/Financeextras/BAO/CreditNote.php
- CRM/Financeextras/BAO/CreditNoteAllocation.php
- tests/phpunit/Civi/Api4/Action/CreditNote/DeleteWithItemsActionTest.php
In this PR we also delete credit note allocations while deleting a credit note entity
Credit note allocations are not deleted
Credit note allocations are deleted
> CIWEMB-465: Delete allocations while deleting credit note

- CRM/Financeextras/Form/Contribute/CreditNoteRefund.php
- Civi/Api4/Action/CreditNote/RefundAction.php
- ang/fe-creditnote/directives/creditnote-allocation-table.directive.js
- templates/CRM/Financeextras/Form/Contribute/CreditNoteRefund.tpl
This PR introduces the following changes to the credit note refund functionality:
1. Align the refund form fields
2. Ensure the refund amount is always in 2 decimal places
> CIWEMB-461: Fix creditnote refund functionality issues

- Civi/Financeextras/Hook/BuildForm/ParticipantCreate.php
- Civi/Financeextras/Hook/PostProcess/ParticipantPostProcess.php
- js/modifyParticipantForm.js
With this PR the Event payment amount is different from the contribution amount.
The Event Contribution uses the payment amount as the contribution amount.
Before
The Event contribution uses the event fee as the contribution amount, and the payment amount is separated.
The issue with the current implementation is that the payment amount entered by the user when creating an event is reflected as the contribution amount instead of the event fee. leading to incorrect contribution status. For example, if the payment amount is greater than the contribution amount(i.e. the event fee), the contribution status should be `pending refund`, or if the contribution amount is less than the payment amount the contribution status should be `partially paid`, but instead the contribution status is always …
> CIWEMB-468: Allow Event contribution amount to be different from payment amount

- CRM/Financeextras/BAO/CreditNoteLine.php
- css/fe-creditnote.css
- tests/phpunit/Civi/Api4/Action/CreditNote/CreditNoteSaveActionTest.php
- tests/phpunit/Civi/Api4/Action/CreditNote/RefundActionTest.php
- tests/phpunit/Civi/Api4/Action/CreditNote/VoidActionTest.php
- tests/phpunit/Civi/Financeextras/Service/CreditNoteInvoiceServiceTest.php
This PR majorly corrects the financial item accounting entry that had the wrong status, and also (UI update) added a separator to the credit note list menu items.
The financial item status for credit note line is `0`
```json
{
"id": 168,
"created_date": "2023-08-30 14:35:57",
"transaction_date": "2023-08-30 00:00:00",
"contact_id": 22,
"description": "Contribution Amount - Taax",
"amount": -40,
"currency": "GBP",
"financial_account_id": 15,
"status_id": 0,
"entity_table": "financeextras_credit_note_line",
"entity_id": 8
}
```
No separator can be seen between the action items.
The financial item status for credit note line is `3` - `Unpaid`
```json
{
"id": 188,
"created_date": "2023-09-05 09:08:30",
"transaction_date": "2023-09-05 00:00:00",
"contact_id": 2,
"description": "Polikok", …
```
> CIWEMB-463: Ensure financial item accounting entry has the right status

- ang/fe-creditnote/directives/creditnote-allocation-table.directive.js
This PR displays a confirmation box to the user before deleting a credit note allocation.
No confirmation box was displayed when deleting a credit note allocation
A confirmation box is displayed before deleting a credit note allocation
> CIWEMB-446: Display confirmation box before deleting allocation

- CRM/Financeextras/BAO/CreditNoteAllocation.php
When a credit note allocation is reversed, we need the contribution status to reflect that the payment has been refunded
In a previous pull request, https://github.com/compucorp/io.compuco.financeextras/pull/56, we introduced an event that enables the reevaluation of contribution status based on the total payment amount. Then in a subsequent pull request,  https://github.com/compucorp/io.compuco.financeextras/pull/73, we invoke this event within a hook. This configuration ensures that the event is triggered whenever a contribution is updated.
However, when it comes to credit note functionalities such as refunds or allocation reversals, it becomes necessary to manually initiate this event after performing these specific actions. This is essential because the contribution hook will not be …
> CIWEMB-480: Update contribution status on allocation reverse

- CRM/Financeextras/Hook/Links/Contribution.php
- ang/fe-creditnote/directives/creditnote-create.directive.html
- ang/fe-creditnote/directives/creditnote-create.directive.js
- templates/CRM/Financeextras/Form/Contribute/CustomLineItem.tpl
This PR updates the CiviCRM contribution edit screen to display as expected, also it introduces the following changes
- Disable the creditnote currency field when the form is prefilled from a contribution.
- Restrict statuses where the `Add Credit Note` link will be added to a contribution.
- Prevent a user from adding a line item to a contribution created from price set in the edit screen.
*Prevent a user from adding a line item to a contribution created from the price set in the edit screen.*
> CIWEMB-466: Update Contribution edit screen

- CRM/Financeextras/Form/Contribute/CreditNoteAllocate.php
- ang/fe-creditnote/directives/creditnote-view.directive.html
This PR ensures previous alert messages are not displayed when a user clicks the back button on the contribution view screen
Alert displayed on cancel button click
Alert not displayed on cancel button click
> CIWEMB-494: Clear alert on credit note view cancel

- CRM/Financeextras/BAO/CreditNote.php
- ang/fe-creditnote/directives/creditnote-allocation-table.directive.js
- financeextras.php
Previously the tax amount was not included when splitting the refund amount between credit note line items, in this PR we ensure the tax amount is included in the split value.
We also reduced the allocation delete modal size.
> CIWEMB-463: Include tax amount in refund calculation

- Civi/Financeextras/Event/Listener/ContributionPaymentUpdatedListener.php
- Civi/Financeextras/Hook/PostProcess/ContributionPostProcess.php
This PR ensures the Contribution status update logic only runs when the contribution has specific statuses.
Previously the status update logic attempted to update the contribution status based on the amount paid, irrespective of the contribution status, For example, if a contribution status is cancelled and all the payments are paid, it will update the contribution status to `Completed`.
In this PR we ensure this doesn't happen, by limiting the update logic to only run when the contribution is of any of these statuses `[Pending', 'Completed', 'Partially paid', 'Refunded', 'Pending refund']`
> CIWEMB-305: Only update contribution status for specific status

- CRM/Financeextras/Form/Contribute/CreditNoteAllocate.php
- Civi/Financeextras/Hook/AlterMailParams/AlterContributionReceipt.php
- financeextras.php
- js/modifyContributionForm.js
- templates/CRM/Financeextras/Form/Contribute/CustomLineItem.tpl
- templates/CRM/Financeextras/Form/Event/AddContribution.tpl
This PR introduces the following changes
- Update the Allocation close button label to skip
- Allow user to set new contribution currency
- Display contribution amount in 2 dp
- Ensure the contribution receipt shows the correct total
- Align contribution payment fields
_The allocation close button label shows cancel_
_User cannot set new contribution currency_
_Contribution payment amount is not in 2 dp_
_ The contribution receipt shows the total as 0.00_
_The allocation close button label changed to skip_
_Allow user to set new contribution currency_
_Display contribution amount in 2 dp_
_ Ensure the contribution receipt shows the correct total_
> CIWEMB-514: Update Contribution and allocation Screen

- sql/auto_install.sql
- xml/schema/CRM/Financeextras/CreditNoteAllocation.xml
This PR ensures that when a contribution is deleted any linked credit note allocation is also deleted.
When a contribution with a credit note allocation is deleted a 500 server error is thrown
When a contribution with a credit note allocation is deleted, the linked allocations are also deleted.
> CIWEMB-528: Delete allocation on contribution delete

- CRM/Financeextras/BAO/CreditNoteAllocation.php
- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- Civi/Financeextras/Hook/BuildForm/ContributionView.php
- Civi/Financeextras/Hook/BuildForm/MembershipCreate.php
- Civi/Financeextras/Hook/BuildForm/ParticipantCreate.php
- Civi/Financeextras/Hook/PostProcess/AdditionalPaymentPostProcess.php
- Civi/Financeextras/Hook/PostProcess/ContributionPostProcess.php
- Civi/Financeextras/Hook/PostProcess/ParticipantPostProcess.php
- Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php
- financeextras.php
- tests/phpunit/Civi/Api4/Action/CreditNote/DeleteWithItemsActionTest.php
This PR fixes two issues related to contribution not having the right status:
- Contribution having the wrong status after deleting a voided credit note with reversed allocations linked to the contribution.
- Contribution not having the right status after recording a refund.
Also, we restricted the hooks introduced in this extension, to further ensure that they are only triggered for the appropriate actions.
Contribution still has a completed status after the refund.
Contribution has a partially paid status after a partial refund.
After a complete refund, the contribution has a pending pay later status.
We have not included a screen recording of this issue `Contribution having the wrong status after deleting a voided credit note with reversed allocations linked to the contribution.` …
> CIWEMB-525: Fix contribution status post refund and credit note delete

- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- js/modifyContributionForm.js
- js/modifyParticipantForm.js
- templates/CRM/Financeextras/Form/Contribute/AddPayment.tpl
For the Credit Card contribution screen, we hide the record payment checkbox added by the extension, since recording of payment is mandated.
Beyond hiding, we also disable JS logics related to the record payment checkbox
The record payment checkbox is visible
The record payment checkbox is not visible
This PR also introduces a new change to the event registration screen; a header is added to the registration note field.
> CIWEMB-523: Hide Record payment field for live contributions

- Civi/Financeextras/Service/CreditNoteInvoiceService.php
- templates/CRM/Financeextras/MessageTemplate/CreditNoteInvoice.tpl
This PR introduces two changes to the Credit note invoice
- Ensure reversed allocations are excluded from the credit note allocations list
- Remove the contribution page hyperlink
> CIWEMB-517: Update CreditNote Invoice

- Civi/Api4/Action/Currency/FormatAction.php
- Civi/Api4/Currency.php
- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- js/modifyContributionForm.js
- templates/CRM/Financeextras/Form/Contribute/CustomLineItem.tpl
In this PR we add a custom total amount label to the new and edit contribution screen. This allows us to resolve two issues, which are:
1. The displayed total amount does not reflect the selected currency on the new contribution screen.
2. The total contribution amount for a price set doesn't include the tax amount.
It's worth mentioning that these are core issued, and there could be a requirement to eliminate this temporary solution in the coming days once it gets resolved in CiviCRM.
The two issues mentioned above are reproducible as shown in the video below
The two issues mentioned above are no longer reproducible as shown in the video below
One of the major issues with updating the total amount when the currency changes is the difficulty in formatting the value appropriately.
To …
> CIWEMB-520: Add custom Total Amount

- CRM/Financeextras/BAO/CreditNoteAllocation.php
- CRM/Financeextras/Upgrader.php
- Civi/Financeextras/Setup/Manage/CreditNotePaymentInstrumentManager.php
- tests/phpunit/Civi/Api4/Action/CreditNoteAllocation/AllocateActionTest.php
- tests/phpunit/Civi/Api4/Action/CreditNoteAllocation/ReverseActionTest.php
This PR adds a payment instrument/method named `Credit note`, this payment instrument will be used for credit note allocations
The credit note allocations use `credit card` as the payment instrument for credit note allocations
The credit note allocations use `credit note` as the payment instrument for credit note allocations
> CIWEMB-529: Credit note payment method

- templates/CRM/Financeextras/Form/Contribute/CustomLineItem.tpl
- templates/CRM/Financeextras/MessageTemplate/CreditNoteInvoice.tpl
This PR prevents the user from adding a new item on a price set contribution in the edit screen.
The second commit [CIWEMB-532: Fix validation error in quotation invoice](https://github.com/compucorp/io.compuco.financeextras/pull/105/commits/08d0098a1b462d9189674acb8158fcd9b938c58e) is to fix a smarty validation error reported during the unit test, no visual changes.
> CIWEMB-532: Preventing adding of new item on priceset contribution

- CRM/Financeextras/BAO/CreditNote.php
- CRM/Financeextras/BAO/CreditNoteAllocation.php
- CRM/Financeextras/BAO/CreditNoteLine.php
- CRM/Financeextras/Form/Contribute/CreditNoteAllocate.php
- CRM/Financeextras/Form/Contribute/CreditNoteRefund.php
- CRM/Financeextras/Hook/Links/Contribution.php
- CRM/Financeextras/Hook/PageRun/ContributionPageTab.php
- Civi/Api4/Action/CreditNote/CreditNoteSaveAction.php
- Civi/Api4/Action/CreditNote/GetAction.php
- Civi/Financeextras/APIWrapper/SearchDisplayRun.php
- Civi/Financeextras/Event/Listener/ContributionPaymentUpdatedListener.php
- Civi/Financeextras/Event/Subscriber/CreditNoteInvoiceSubscriber.php
- Civi/Financeextras/Hook/AlterMailParams/AlterContributionReceipt.php
- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- Civi/Financeextras/Hook/BuildForm/ContributionView.php
- Civi/Financeextras/Hook/BuildForm/ParticipantCreate.php
- Civi/Financeextras/Hook/PostProcess/ParticipantPostProcess.php
- Civi/Financeextras/Hook/ValidateForm/FinancialTypeAccount.php
- Civi/Financeextras/Service/CreditNoteInvoiceService.php
- Civi/Financeextras/Setup/Configure/SetDefaultCompany.php
- ang/fe-creditnote.ang.php
- financeextras.php
When enabling the extension inside and upgrader that runs during deployment, the default Company that is supposed to be created according to the work in this PR: https://github.com/compucorp/io.compuco.financeextras/pull/94 is not getting created.
The default Company is getting created normally when installing the extension during deployment.
In this class:
Civi/Financeextras/Setup/Configure/SetDefaultCompany.php
I create the default Company using API v4, but API v4 by default enforce permission check, but most of the time API calls that are done from the backend do not need a permission check, given most of the time other permissions are enforced at higher level so these API calls are already being executed from safe contexts.
And while the motivating for the work I did here was the …
> CIWEMB-322: Remove unnecessary permission checks

- CRM/Financeextras/Upgrader.php
- tests/phpunit/CRM/Financeextras/Form/Company/AddTest.php
- tests/phpunit/CRM/Financeextras/Form/Company/DeleteTest.php
- tests/phpunit/CRM/Financeextras/Page/CompanyTest.php
Despite the work here: https://github.com/compucorp/io.compuco.financeextras/pull/113
the default company is still not getting created on fresh installation, and while I mentioned that it works now in that PR, that's because Financeextras is installed by default on Compuclient sites, so I thought that things are working fine, but if you uninstall the extension then try to install it again then the default Company won't be created.
Installing the extension on a fresh site, or uninstalling then installing the extension creates the default Company correctly:
I used `\Civi\Api4\Company::create(FALSE)` v4 API to create the default Company, but when the `install()` hook runs this API is not loaded yet given the extension is not yet fully installed, and because I already ignore any exceptions …
> CIWEMB-323: Fix default company creation on fresh site

- CRM/Financeextras/BAO/CreditNoteAllocation.php
- js/modifyContributionForm.js
This PR Ensure the successful deletion of a voided credit note and also updates the send receipt label of the new contribution form
> CIWEMB-525: Ensure the successful deletion of a voided credit note

- xml/customFields_install.xml
This PR adds VAT text custom field to the currency exchange rate custom group
> ESEB-69: Add VAT text custom field

- CRM/Financeextras/Upgrader.php
- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- Civi/Financeextras/Hook/BuildForm/MembershipCreate.php
- Civi/Financeextras/Hook/BuildForm/ParticipantCreate.php
- Civi/Financeextras/Hook/PostProcess/ParticipantPostProcess.php
- Civi/Financeextras/Setup/Manage/AccountsReceivablePaymentMethod.php
- js/modifyContributionForm.js
- js/modifyMemberForm.js
- js/modifyParticipantForm.js
Adding new payment method `Accounts Receivable` which will be used as the default payment method for contributions that are created without recording a payment.
When creating a contribution , membership (non payment plan), or registering an event participant from the admin form, the resulting contribution will have the default payment method in CiviCRM set as the contribution payment method.  
The `Accounts Receivable`  payment method will be used by default for contributions created  without recording a payment.
The Contribution form:
https://github.com/compucorp/io.compuco.financeextras/assets/6275540/eb5c8e9a-a0c7-4ccf-a7d0-8fe12356f9a9
The Membership form (Without Payment plan):
https://github.com/compucorp/io.compuco.financeextras/assets/6275540/b49a056a-3024-4051-b1ef-6b810c00fadd …
> CIWEM-18: Enforce 'Account Receivable' payment method for pending contributions

- Civi/Financeextras/Hook/AlterMailParams/InvoiceTemplate.php
- Civi/Financeextras/Hook/PostProcess/UpdateContributionExchangeRate.php
- financeextras.php
- templates/CRM/Financeextras/MessageTemplate/SalesTaxConversionRateTable.tpl
- tests/phpunit/Civi/Financeextras/Hook/AlterMailParams/InvoiceTemplateTest.php
- xml/customFields_install.xml
This PR adds a new token `{contribution.tax_exchange_rate_table}`, which, when added to the contribution invoice template, will display the contribution exchange rate VAT table and VAT text.
_N/A_
Adding the token to the contribution invoice template
The Exchange rate table being displayed
The Exchange rate table and VAT text are dispalyed
> ESEB-67: Add sales tax conversion table token

- CRM/Financeextras/Form/ExchangeRate/Settings.php
- Civi/Financeextras/Hook/AlterMailParams/InvoiceTemplate.php
- Civi/Financeextras/Hook/PostProcess/LocalizationPostProcess.php
- Civi/Financeextras/Hook/PostProcess/UpdateContributionExchangeRate.php
- financeextras.php
This PR introduces multiple fixes to ensure the contribution invoice has a valid exchange rate table
- [Ensure sales tax currency option group ID is always up to date](https://github.com/compucorp/io.compuco.financeextras/commit/9e32e5d7e05c299da3a8a3c35f26fe6ca7ce28d1)
- [Ensure the user cannot save empty tax currency settings](https://github.com/compucorp/io.compuco.financeextras/commit/68b390d9357dd0165ccb30a1c69cc66a032b6924)
- [Ensure tax conversion table is displayed](https://github.com/compucorp/io.compuco.financeextras/commit/917e421e88d639e095e8b5253b7e159070338a2a)
- [Use most recent exchange rate](https://github.com/compucorp/io.compuco.financeextras/commit/682e11a99ae026481b3b57297b2f29dea5297ec4)
The exchange rate on the invoice is not correct, and the sales tax currency is …
> ESEB-66: Ensure the contribution invoice have the valid exchange rate table

- js/modifyMemberForm.js
As part of the work we did here: 
https://github.com/compucorp/io.compuco.financeextras/pull/58
we no longer show the payment method and some of the payment related fields unless the user clicks on the "Record Payment" option, which is an option that is only added for non payment plan memberships:
https://github.com/compucorp/io.compuco.financeextras/assets/6275540/b026cfe9-6bb3-4226-a634-b104584322e2
But apparently the work in the PR above also affected the payment plan screen which used to show the payment method field, given without it the user cannot create [manual direct debit](https://github.com/compucorp/uk.co.compucorp.manualdirectdebit) payment plans. 
The Payment method field now shows up if the user selects the "payment plan" option on the membership creation form: …
> COMCL-431: Show payment method field for payment plan memberships

- CRM/Financeextras/BAO/CreditNoteAllocation.php
- CRM/Financeextras/Form/Contribute/CreditNoteAllocate.php
- CRM/Financeextras/Form/Contribute/CreditNoteEmail.php
- CRM/Financeextras/Form/Contribute/CreditNoteRefund.php
- Civi/Api4/Action/CreditNote/DeleteWithItemsAction.php
- Civi/Api4/Action/CreditNote/VoidAction.php
- Civi/Financeextras/Service/CreditNoteInvoiceService.php
- Civi/Financeextras/Utils/OptionValueUtils.php
- ang/fe-creditnote.ang.php
When an anonymous user tries to submit a contribution page configured with GoCardless, an error saying "Authorization Failed" is thrown. This issue is fixed with this PR.
The that shows up in the logs is the following:
```
-- | -- | --
  |   | 2023-11-27 15:53:49.944 | /var/www/default/htdocs/httpdocs/index.php:21 { …} |  
  |   | 2023-11-27 15:53:49.944 | /var/www/default/htdocs/httpdocs/includes/menu.inc:527 { …} |  
  |   | 2023-11-27 15:53:49.944 | /var/www/default/htdocs/httpdocs/profiles/compuclient/modules/contrib/civicrm/drupal/civicrm.module:471 { …} |  
  |   | 2023-11-27 15:53:49.944 | /var/www/default/htdocs/httpdocs/profiles/compuclient/modules/contrib/civicrm/CRM/Core/Invoke.php:36 { …} |  
  |   | 2023-11-27 15:53:49.944 | …
```
> COMCL-409: Remove unnecessary API 4 backend permission checks

- CRM/Financeextras/Form/Contribute/CreditNoteEmail.php
- Civi/Financeextras/Token/CreditNote.php
- financeextras.php
This pr adds credit note tokens while emailing the credit note.
There were no credit note tokens to be used in subject or body of the email.
> CIWEMB-569: Add Credit Note Tokens

- CRM/Financeextras/Form/Contribute/CreditNoteRefund.php
- Civi/Financeextras/Hook/BuildForm/RefundCreditNotePaymentInformation.php
- financeextras.php
This pr changes the following things in refund credit note form.
- Correct the label for cheque number field
- Disable the contact field
- Add arrow to the payment method dropdown
> CIWEMB-518 Adapt Refund Credit Note Form

- Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php
- js/modifyContributionForm.js
This pull request addresses the issue of the credit card contribution total displaying zero. 
The problem arose due to the lack of explicit support for line items in the line item edit extension. Instead, users were expected to enter an amount in the total amount field. But, with this commit (https://github.com/compucorp/io.compuco.financeextras/commit/18810f80ea7cf95961f0108c0d90c438c4f98638), we have transitioned to using line items by default in the new contributions screen, and the total amount field hidden. in this pull request, the credit card contribution total amount  is now manually set based on the line item total.
The credit card contribution total amount was displaying as zero.
The credit card contribution total amount now reflects the correct value.
> COMCL-405: Ensure credit card contribution has correct total

- CRM/Financeextras/Form/Payment/Refund.php
Add payment processor id and name to a refund record in database. while creating refund 
These column values were not getting saved for refund.
Values are saved correctly.
> CIVIPLUSI-18: Add Payment Processor Info To Refund Record

- Civi/Financeextras/Refund/PaymentProcessor.php
This pr fixes a code glitch which caused any contribution page to error out.
[screencast-myisrael.civiplus.net-2024.01.29-08_49_49.webm](https://github.com/compucorp/io.compuco.financeextras/assets/147053234/c1d52f94-7db5-4f28-8157-d2dd3e9fe82a)
The issue occurred due to a bug in code as we were treating a processor variable as object but it can be null as well if the class name in the database for a processor does not fully match the class name for processor in code
> MAE-1105: Fix Contribution Bug

- CRM/Financeextras/BAO/CreditNoteAllocation.php
- CRM/Financeextras/Form/Contribute/CreditNoteAllocate.php
- templates/CRM/Financeextras/Form/Contribute/CreditNoteAllocate.tpl
- tests/phpunit/Civi/Api4/Action/CreditNoteAllocation/AllocateActionTest.php
This PR allows the user to allocate credit to a completed(fully paid) contribution
Completed contributions do not appear in the credit allocation screen, hence users are not able to allocate credit to them.
With this PR, the user can allocate credit to completed contributions in the credit allocation screen.
> CIWEMB-580: Support credit allocation to completed contribution

- Civi/Financeextras/Hook/ValidateForm/ContributionEdit.php
- financeextras.php
This PR prevents the user from updating the financial type of a contribution, we are doing this because when a contribution financial type is changed on edit the contribution is likely to have incorrect tax calculations.
This happens because on edit the core gets tax of the new financial type and adds it to the contribution total. these validation already exist for contributions with multiple line items https://github.com/civicrm/civicrm-core/blob/42cb6102f3ed25cf9d2438ca8eeb815c3a04f9eb/CRM/Contribute/BAO/Contribution.php#L3681, this PR extends this check to a single line item.
> CIWEMB-466: Prevent user from updating contribution financial_type

- CRM/Financeextras/Page/AJAX.php
- Civi/Financeextras/Hook/AlterContent/BatchTransaction.php
- js/addContributionCreditNoteBtn.js
This PR ensures credit note transactions are also listed on the batch transaction page
Only contribution transactions are listed on the batch transaction page, and the financial type column is visible
Contributions and credit notes transactions are listed on the batch transaction page, and we also hid the financial type column.
We update `CRM/Financial/Form/BatchTransaction` to use our custom getFinancialTransactionList Ajax method by updating the template file in the `AlterContent` hook
From
`q="className=CRM_Financial_Page_AJAX&fnName=getFinancialTransactionsList&snippet=4&context=financialBatch&entityID=$entityID&statusID=$statusID"`
To 
`q="className=CRM_Financeextras_Page_Financial_AJAX&fnName=getFinancialTransactionsList&snippet=4&context=financialBatch&entityID=$entityID&statusID=$s …
> CIWEMB-583: Include creditnote in batch transaction

- Civi/Financeextras/Hook/BuildForm/MembershipCreate.php
This PR avoids unnecessarily loading payment plan settings for submit credit card membership form.
In this [PR] (https://github.com/compucorp/io.compuco.financeextras/pull/58)we added the ability to create a membership without a payment, and there it was assumed that `contribution_type_toggle`
input that allows selecting between a contribution or a payment plan is there, but that is not the case for "Submit membership with credit card"
form, given we never supported payment plans on such form before:
https://github.com/compucorp/uk.co.compucorp.membershipextras/blob/6.1.0/CRM/MembershipExtras/Hook/BuildForm/MembershipPaymentPlan.php#L47-L48
so this broke the JS code which in effect resulted in breaking the UI.
In general the ability to select between a free membership and paid membership …
> MAE-1061: Avoid Loading Membership Plan Settings In Submit Credit Card Membership Form

- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
This pr fixes a bug in updation of contribution form due to which the form kept on saving forever. 
The form is being updated successfully.
The Civi/Financeextras/Hook/BuildForm/ContributionCreate.php hook was trying to modify the status field on contribution form but the field was non existent. So a check has been added to modify the field only when field is available in the form.
> COMCL-474: Fix Contribution Status Field Bug

- Civi/Financeextras/Setup/Manage/AccountsReceivablePaymentMethod.php
The "Accounts Receivable" financial account is not a reserved one, yet in this PR (https://github.com/compucorp/io.compuco.financeextras/pull/109/files), we relied on its existence to create the new "Account Receivable" payment method. As with any other payment method in Civi, it should be linked to a financial account. We decided to attach it to the "Accounts Receivable" financial account. This results in a failure in either the extension installation or upgrade if it happens on a CiviCRM site that does not have the "Accounts Receivable" financial account.
This pr aims to change that code to following logic 
Rather than hard coding and just sticking to use the “Accounts Receivable” financial account for creation of **Account receivable** payment method:
- We first try and use Accounts …
> COMCL-488: Fix Extension Upgrade

- CRM/Financeextras/BAO/CreditNote.php
- tests/phpunit/Civi/Api4/Action/CreditNote/CreditNoteSaveActionTest.php
- tests/phpunit/Civi/Api4/Action/CreditNote/VoidActionTest.php
This PR ensures payment method for accounting entries when creating credit notes is “Accounts Receivable”
The payment method for a credit note uses the ID 1 -> which is credit_card on most default installation
```
{
"id": 671,
"total_amount": -48,
"payment_instrument_id:name": "Credit Card"
},
```
The payment method for a credit note is now "Account Receivable"
```
{
"id": 672,
"total_amount": -240,
"payment_instrument_id:name": "accounts_receivable"
},
```
> PROD-173: Use account receivable as creditnote payment instrument

- Civi/Financeextras/Hook/BatchExport/UpdateItems.php
- Civi/Financeextras/Hook/BatchExport/UpdateQuery.php
- financeextras.php
Set invoice number on CSV batch export to credit note number
Credit note transactions exported showed 'INV_' as the invoice number.
| Batch ID | Invoice No | Contact ID | Financial Trxn ID/Internal ID | Transaction Date       |
|----------|------------|------------|-------------------------------|-------------------------|
| 8        | INV_318    | 2          | 650                           | 2024-02-19 00:00:00     |
| 8        | INV_330    | 2          | 652                           | 2024-02-21 13:06:00     |
| 8        | INV_330    | 2          | 652                           | 2024-02-21 13:06:00     |
| 8        | INV_330    | 2          | 652                           | 2024-02-21 13:06:00     |
| 8        | INV_330    | 2          | 652                           | 2024-02-21 …
> PROD-174: Set invoice number on CSV batch export to credit note number

- Civi/Financeextras/Hook/Links/ContributionRecur.php
- Civi/Financeextras/Hook/Links/ContributionRecur/Template.php
- financeextras.php
This pr hides the **view template** action from action menus for a recurring contributions on contact view page if the payment processor for that contribution is either Direct Debit or GoCardless.
> CIWEMB-508: Hide View Template Action For Recurring Contributions

- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- Civi/Financeextras/Hook/BuildForm/ContributionView.php
If contribution has a status of Cancelled, Refunded, Failed or Chargeback then this pr hides the credit note create button from edit and view contribution screens.
> CIWEMB-570: Hide Credit Note Create Button

- Civi/Financeextras/Hook/Links/ContributionRecur/Template.php
This pr fixes a query for a hook that is responsible for removing the **View Template** link for recurring contributions
[This](https://github.com/compucorp/io.compuco.financeextras/blob/master/Civi/Financeextras/Hook/Links/ContributionRecur/Template.php#L38) query resulted in an exception if both gocardless and manual dd extensions are not installed so this pr just catches that exception and returns a false for that function since if both the extensions are not installed then we dont need to remove that link
> CIWEMB-508: Fix 'View Template' Link Removal For Recurring Contributions

- CRM/Financeextras/Form/Payment/Refund.php
- templates/CRM/Financeextras/Form/Payment/Refund.hlp
- templates/CRM/Financeextras/Form/Payment/Refund.tpl
Allow users to create credit notes and allocate the credit notes to the contribution while submitting a credit card refund
There is no option for the user to create a credit note for a credit card refund
Users can now create a credit note for a credit card refund
A credit note is created and allocation is made again to that same contribution
> PROD-156: Create creditnote allocation for credit card refund

- Civi/Financeextras/APIWrapper/SearchDisplayRun.php
- Civi/Financeextras/Hook/BatchExport/UpdateQuery.php
- managed/SavedSearch_SOA_Finance_Report_Beta_v3.mgd.php
This sequel to this PR https://github.com/compucorp/io.compuco.financeextras/pull/154, where we add custom query to set invoice number to credit note number, in this PR we ensure this query altering is limited to CSV export.
> PROD-223: Limit credit note query alter to CSV

- Civi/Financeextras/Hook/Links/ContributionRecur.php
This pr fixes a bug that prevented user from accessing event registration and info pages.
The issue was caused by the type hinting for second parameter as string [here](https://github.com/compucorp/io.compuco.financeextras/blob/master/Civi/Financeextras/Hook/Links/ContributionRecur.php#L61) because its not always a string but sometimes its NULL as well as per the civi [documentation](https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_links/#parameters)
> COMCL-537: Fix Event Registration And Info Pages

- Civi/Financeextras/APIWrapper/Payment.php
- financeextras.php
- tests/phpunit/Civi/Financeextras/ApiWrapper/PaymentTest.php
In this extension we have an [event listener](https://github.com/compucorp/io.compuco.financeextras/blob/master/Civi/Financeextras/Event/Listener/ContributionPaymentUpdatedListener.php) that listens for various events and updates the contribution status according to the payments made against a contribution. Previously this listener did not run when payment apis were called, this pr make this listener to run for payment api calls as well.
This pr calls the listener for following three payment apis
- Create
- Cancel
- Delete
> PROD-230: Run Contribution Status Update Listener When Payment Apis Are Called

- Civi/Financeextras/Hook/Post/ContributionCreation.php
[this](https://github.com/compucorp/io.compuco.financeextras/pull/178) pr updates the contribution's payment method and set it equal to the payment method of the owner organization when a **pay later** contribution is created. But there was a missed scenario due to which the code changes in that previous pr was not identifying the contributions that are created as a result of membership payment plan creation as **pay later** contribution hence not updating the payment method. This pr fixes this gap.
> PROD-240: Update Logic For Contribution's Payment Method Updation To Cater Membership Plan Contributions

- CRM/Financeextras/Hook/PageRun/ContributionPageTab.php
This pr resolves an issue related to contributions that restricted user from creating new contribution or accessing contribution tab on contact view page.
A hook in this extension was accessing a property on CRM_Contribute_Page_Tab class which has been marked as protected in [this](https://github.com/civicrm/civicrm-core/commit/12aabedca0a882b55d6238693fb46859a1920006) commit recently which caused an error upon opening above mentioned pages
> COMCL-643: Fix Contribution Issue

- js/modifyContributionForm.js
- templates/CRM/Financeextras/Form/Contribute/CustomLineItem.tpl
This PR prevents resetting the contribution total amount to zero when the input fields have already been set from the backend.
THis PR is a supplement to this PR https://github.com/compucorp/uk.co.compucorp.civicase/pull/1033
No visual changes
No visual changes
> BTHAMM-31: Prevent resetting contribution total amount to zero

- .github/workflows/tests.yml
- CRM/Financeextras/BAO/CreditNote.php
- CRM/Financeextras/BAO/CreditNoteLine.php
- CRM/Financeextras/Page/Company.php
- Civi/Financeextras/Event/ContributionPaymentUpdatedEvent.php
- Civi/Financeextras/Event/CreditNoteDownloadedEvent.php
- Civi/Financeextras/Event/CreditNoteMailedEvent.php
- templates/CRM/Financeextras/MessageTemplate/CreditNoteInvoice.tpl
- tests/phpunit/Civi/Api4/Action/CreditNote/CreditNoteSaveActionTest.php
- tests/phpunit/Civi/Api4/Action/CreditNote/DeleteWithItemsActionTest.php
- tests/phpunit/Civi/Api4/Action/CreditNote/RefundActionTest.php
- tests/phpunit/Civi/Api4/Action/CreditNote/VoidActionTest.php
- tests/phpunit/Civi/Api4/Action/CreditNoteAllocation/AllocateActionTest.php
- tests/phpunit/Civi/Api4/Action/CreditNoteAllocation/ReverseActionTest.php
- tests/phpunit/Civi/Financeextras/Hook/BuildForm/AdditionalPaymentButtonTest.php
- tests/phpunit/Civi/Financeextras/Hook/PostProcess/FinancialBatchTest.php
- tests/phpunit/Civi/Financeextras/Hook/ValidateForm/ContributionValidatorTest.php
- tests/phpunit/Civi/Financeextras/Payment/RefundTest.php
- tests/phpunit/Civi/Financeextras/Refund/PaymentProcessorTest.php
- tests/phpunit/bootstrap.php
This PR removes methods and class deprecated in 5.75 causing issues such as users being unable to delete credit notes.
Users are unable to delete credit note
https://github.com/user-attachments/assets/75087e66-5091-4705-b21a-5d4956f5b309
Users able to delete credit note
> COMCL-744: Remove methods and class depreceated in 5.75

- CRM/Financeextras/Upgrader.php
- Civi/Financeextras/Hook/Post/UpdateLineItemPriceFieldValues.php
- financeextras.php
This pr fixes the creation of line item that gets created without price field values as with newer civicrm version it is mandatory for a line items to have price field values.
This pr adds a post hook that runs every time a line item is created without price field values and it updates the line item with price field value from default price set(the price set by the name of **default_contribution_amount**), this price set is created with civicrm installation. Secondly this pr also adds an upgrader which will fill price field values for existing line items.
> COMCL-770: Fix Line Item Creations

- ang/fe-creditnote/directives/creditnote-allocation-table.directive.js
This pr fixes a bug on view credit note page due to which the remaining amount and allocated amount were shown to users as NAN when the quantity in line item is selected as 0
> COMCL-802: Fix Amounts Display On View Credit Note Page

- js/modifyMemberForm.js
Prevent the retriggering of the payment plan checkbox multiple times
> COMCL-850: Prevent retriggering of the payment plan checkbox multiple times

- CRM/Financeextras/Upgrader.php
- Civi/Financeextras/Hook/Post/UpdateLineItemPriceFieldValues.php
After this PR (https://github.com/compucorp/io.compuco.financeextras/pull/193), we had issues with failing upgraders during site deployment on existing sites with more price fields due to the method https://github.com/civicrm/civicrm-core/blob/2998081bf4b990739ddfcec0b9dd7d9e6c4e7a40/CRM/Price/BAO/PriceSet.php#L515 and https://github.com/civicrm/civicrm-core/blob/2998081bf4b990739ddfcec0b9dd7d9e6c4e7a40/CRM/Price/BAO/PriceSet.php#L530 used. We now manually fetch the price field and price field values  of the price set.
_no visual changes_
_no visual changes_
> COMCL-770: Use the price field and price field value of default priceset

- Civi/Financeextras/Hook/PostProcess/ContributionPostProcess.php
After we separated the payment from contribution, the payment now separately sends a receipt to the user even though the contribution creation process will still send a receipt to the user, which will also consider whether the user checks the "Email Confirmation" box or not.
The payment recording process sends a payment receipt to the user during payment creation.
The payment recording process no longer sends a payment receipt to the user during payment creation. Instead, the contribution recording process handles sending receipts to users, considering their preference for receiving email confirmations.
This happens because the default value of is_send_contribution_notification to the payment.create API is TRUE, we need to set it to FALSE and let the contribution recording process decide …
> CIVIPLMMSR-302: Prevent sending multiple payment receipts

- Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php
- js/modifyContributionForm.js
- templates/CRM/Financeextras/Form/Contribute/CustomLineItem.tpl
This PR is a follow-up to this PR https://github.com/compucorp/lineitemedit/pull/15 where we resolve an issue with credit card payment and the line item editor extension.
Here we ensure we compute the correct total from the line items.
Also we corrected the issue with the "Price set selector" field appearing twice
> COMCL-861: Calculate live credit card payment total from line items

- Civi/Financeextras/Hook/Post/UpdateLineItemPriceFieldValues.php
- financeextras.php
[here](https://github.com/compucorp/io.compuco.financeextras/pull/198) we added a hook and an upgrader to update the line item's price field and price field value ids, this pr makes the code more consistent between upgrader and hook.
> CIVIPLMMI-189: Align Hook With Upgrader Code

- CRM/Financeextras/BAO/CreditNoteAllocation.php
Prevent Membership End Date Extension After Credit Note Allocation
The membership end date is extended after credit note allocation.  
The membership end date is no longer extended after credit note allocation.  
In CiviCRM, when a payment is made to a contribution linked to an entity, the entity is updated. However, this is not the expected behavior for memberships. For more details, refer to this PR: [#485](https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/485), where we addressed this for standard payments. However, the PR did not cover credit note allocations, as these do not use the standard payment API but instead manually create the necessary payment entities.
In this PR, we have added the required check to ensure the membership end date is not extended when a …
> CIVIMM-213: Prevent extending Membership end date post credit note allocation

- ang/fe-creditnote/directives/creditnote-create.directive.js
Currently in a scenario where the owner organization on a contribution is empty and user tries to create a credit note for this contribution the owner organization field gets disabled on the credit note creation form and empty at the same time not allowing the user to create the credit note.
User is allowed to select the owner organization if there are more than one comapny otherwise the available one company is selected and field gets disabled as shown below
> CSTMM-43: Fix Owner Organization Field On Credit Note Creation

- Civi/Financeextras/APIWrapper/SearchDisplayRun.php
- managed/SavedSearch_SOA_Finance_Report_Beta_v3.mgd.php
This PR converts the SOA tax amount to 2DP without rounding up, this is in a bid to ensure the tax amount calculated correlates with the tax amount  in the database as shown in the other financial reports
The computed tax amount for the line item with `Net Amount` of 116.78 shows as 23.36
The computed tax amount for the line item with `Net Amount` of 116.78 shows as 23.35, which correlates with what is reported in other reports.
> PROD-229: Convert tax amount to 2DP without rounding up

- info.xml
- settings/insurancepremium.setting.php
This pr adds a setting to **civicontribute component settings** page to select any financial type for identifying insurance premium line items in a contribution.
The settings does not exist.
> MMB-500: Add Settings For Insurance Premium Financial Type

- Civi/Financeextras/Hook/PostProcess/ParticipantPostProcess.php
In [this](https://github.com/compucorp/io.compuco.financeextras/pull/74/commits/1afd536704fc470b1104e0145e06d53b86231b49) commit we created a contribution record for registering a participant but currently when user registers a participant through register participant form the financial item entry does not get created due to which information in bookkeeping reports are missing. This pr fixes the issue by creating relevant financial item entry after the participant has been registered.
> CIVIMM-270: Fix Participant Registering

- Civi/Financeextras/Hook/BuildForm/PaymentCreate.php
- financeextras.php
- js/modifyContributionForm.js
- js/modifyMemberForm.js
- js/modifyParticipantForm.js
In [this](https://github.com/compucorp/io.compuco.financeextras/pull/109) pr we fixed the **account receivable** payment method for contributions that will be created as pending but same pr also created a bug in which **account receivable** was getting selected for completed contributions as well even though the default payment method was selected as something else. This pr fixes this issue and now for contributions that tends to record payment have default payment method as selected by default on page load where as for pending contributions the **account receivable** is selected by default.
> CIVIPLMMSR-383: Respect Default Payment Method On Contribution Pages

- CRM/Financeextras/Upgrader.php
- Civi/Financeextras/Service/IncompleteContributionFixService.php
- tests/phpunit/Civi/Financeextras/Service/IncompleteContributionFixServiceTest.php
- tests/phpunit/Civi/Financeextras/Test/Fabricator/MembershipFabricator.php
- tests/phpunit/Civi/Financeextras/Test/Fabricator/MembershipTypeFabricator.php
This pr adds an upgrader to fix the faulty contribution records that does not have any line item attached to it.
Such contributions gets created when a membership record is first created without a recurring contribution and then renewed with a contribution in CiviCRM. Systems who are migrated from another CRM and don’t have recurring contributions associated with memberships will likely experience this issue.
The root cause of this issue is renewing memberships without prior contribution (or if CiviCRM cannot find the contribution), the contribution created for the membership renewal will not have the appropriate line items.
This pr fixes these records by creating appropriate financial transactions, line items and financial items as well. Although it is possible that in past there were …
> CIVIPLMMSR-418: Add Upgrader To Fix Faulty Contributions

- CRM/Financeextras/Settings.php
- ang/fe-creditnote.ang.php
Previously all the settings needed for angular pages was being passed as plain array but to be compatible with new civicrm version the settings are being migrated to a settings class which fixes a warning on civicrm status page about unsupported settings.
No such warnings are displayed
> COMCL-953: Move Angular Settings For Credit Note To Settings Class

- CRM/Financeextras/Upgrader.php
- Civi/Financeextras/Setup/Manage/CreditNoteInvoiceTemplateManager.php
This PR fixes an issue that restricted user from emailing or downloading a credit note.
The users were not able to download or email a credit note.
Users can download or email a credit note successfully.
This issue was due to a syntax error in credit note template which will be fixed by this pr.
> COMCL-1031: Fix Credit Note Template

- Civi/Financeextras/Hook/AlterMailContent/ContributionTemplate.php
- Civi/Financeextras/Hook/AlterMailParams/InvoiceTemplate.php
- financeextras.php
- tests/phpunit/Civi/Financeextras/Hook/AlterMailParams/InvoiceTemplateTest.php
The Multicompany accounting feature in this extension allows site administrators to select a message template for contribution invoices based on the contribution owner's organization (i.e., company).  
After upgrading to CiviCRM 5.75.1, this functionality broke because the underlying logic changed. Previously, the `alterMailParams` hook was triggered before rendering the template, allowing us to swap the message template ID dynamically. However, in the latest CiviCRM version, the hook is now called after the template has already been rendered, preventing this approach from working.  
Relevant changes:  
- Previous implementation (worked as expected): [[CiviCRM 5.39.1 - MessageTemplate.php#L418](https://github.com/civicrm/civicrm-core/blob/5.39.1/CRM/Core/BAO/MessageTemplate.php#L418)](http …
> BTHAMM-61: Update mail content with organisation mail template

- Civi/Financeextras/Hook/BuildForm/ContributionView.php
This PR remove **Download Invoice** and **Email Invoice** buttons from the view contribution screen if the contribution has a status equal to **Cancelled** or **Failed**
> CIVIMM-320: Remove Download Invoice And Email Invoice Buttons

- CRM/Financeextras/Form/Contribute/ContributionVoid.php
- Civi/Financeextras/Hook/BuildForm/ContributionView.php
- Civi/Financeextras/Hook/Links/Contribution/CreditNote.php
- js/addContributionVoidBtn.js
- templates/CRM/Financeextras/Form/Contribute/ContributionVoid.tpl
- xml/Menu/financeextras.xml
This PR adds the ability for users to void a contribution. We add an extra link to the contribution list context menu, and also on the contribution view screen
The Void option doesn't exist on the context menu and contribution view screen
The `Void Contribution` button is available for all contribution statuses except Failed, Completed, Cancelled, and when the contribution is not linked to any payment transaction.
The void is done by changing the contribution status to cancelled using the APIv4, allowing CiviCRM to perform every other necessary default actions for a cancelled contribution.
> CIVIMM-318: Add ability to void contributions

- ang/fe-creditnote/directives/creditnote-create.directive.html
- ang/fe-creditnote/directives/creditnote-create.directive.js
- css/fe-creditnote.css
This PR disables contact field when creating a credit note from an invoice or from a contact record.
> CIVIMM-352: Disable Contact Field On Create Credit Note Form

- Civi/Financeextras/Hook/BuildForm/FinancialBatch.php
- js/financialbatch.js
This PR fixes the application of owner organization filter during the accounting batch creation as currently when user applies the owner organization filter it does not get applied to search criteria while filtering the transactions. Also this PR corrects the positioning of the field as the field is currently placed outside of the box.
> CIVIMM-315: Fix Owner Organization Filter Application

- Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php
When the tax and invoicing component is not enabled, we want to ensure the line total is still calculated as expected.
Previously the error below is thrown
> Argument #1 ($array) must be of type array, null given in array_sum() (line 48 of /var/www/default/htdocs/httpdocs/profiles/compuclient/modules/contrib/civicrm/ext/io.compuco.financeextras/Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php)
> COMCL-1109: Ensure total can be calculated when tax component is not enabled

- CRM/Financeextras/Form/Contribute/ContributionVoid.php
- Civi/Financeextras/Hook/BuildForm/ContributionView.php
- Civi/Financeextras/Hook/Links/Contribution/CreditNote.php
- templates/CRM/Financeextras/Form/Contribute/ContributionVoid.tpl
This PR allows users to void completed contributions, a continuation of this [PR](https://github.com/compucorp/io.compuco.financeextras/pull/234).
No void contribution option on completed contributions
Users can now void completed contributions
> CIVIMM-353: Allow user to void completed contribution
