- .github/workflows/linters.yml
- bin/install-php-linter
- phpcs-ruleset.xml
This PR adds PHP CS linters action and ruleset to the repo.
> CIWEM-15: Add phpcs linter action and ruleset

- .github/workflows/tests.yml
- phpunit.xml.dist
- tests/phpunit/BaseHeadlessTest.php
- tests/phpunit/Civi/Financeextras/Test/Fabricator/AbstractBaseFabricator.php
- tests/phpunit/Civi/Financeextras/Test/Fabricator/ContactFabricator.php
- tests/phpunit/Civi/Financeextras/Test/Fabricator/ContributionFabricator.php
- tests/phpunit/Civi/Financeextras/Test/Fabricator/PaymentProcessorFabricator.php
- tests/phpunit/bootstrap.php
This PR setups PHPUnit test for this project and adds few initial fabricators
> CIWEM-15: Add unit test skeleton

- .eslintrc.json
- .github/workflows/linters.yml
- .github/workflows/tests.yml
- .gitignore
- package-lock.json
- package.json
This PR adds ES Lint for JS style checking and also updates the testing workflow to PHP 8 container
> CIWEMB-289: Add ESLint and Update GitHub action

- .github/workflows/tests.yml
- CRM/Financeextras/Form/Payment/Refund.php
- CRM/Financeextras/Hook/BuildForm/AdditionalPaymentButton.php
- Civi/Financeextras/Hook/Links/Contribution.php
- Civi/Financeextras/Hook/Links/Contribution/Refund.php
- Civi/Financeextras/Payment/Refund.php
- Civi/Financeextras/Refund/PaymentProcessor.php
- README.md
- api/v3/PaymentProcessor/GetRefundedAmount.php
- css/custom-civicrm.css
- financeextras.php
- js/custom.js
- templates/CRM/AdditionalPayment/Form/Payment/RefundButton.tpl
- templates/CRM/Financeextras/Form/Payment/Refund.tpl
- tests/phpunit/Civi/Financeextras/Hook/BuildForm/AdditionalPaymentButtonTest.php
- tests/phpunit/Civi/Financeextras/Payment/RefundTest.php
- tests/phpunit/Civi/Financeextras/Refund/PaymentProcessorTest.php
- xml/Menu/financeextras.xml
This PR merges Stripe refund workstream branch to master branch
> CIVIIB-154: Merge workstream branch to master for Stripe refund release. 

- info.xml
This PR bumps version 1.0.0 for release
> CIVIIB-163: Update info.xml for releasing version 1.0.0

- Civi/Financeextras/Event/ContributionPaymentUpdatedEvent.php
- Civi/Financeextras/Event/Listener/ContributionPaymentUpdatedListener.php
- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- Civi/Financeextras/Hook/BuildForm/ContributionView.php
- Civi/Financeextras/Hook/BuildForm/MembershipCreate.php
- Civi/Financeextras/Hook/BuildForm/ParticipantCreate.php
- Civi/Financeextras/Hook/PostProcess/ContributionPostProcess.php
- Civi/Financeextras/Hook/PostProcess/ParticipantPostProcess.php
- Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php
- Civi/Financeextras/Hook/ValidateForm/MembershipCreate.php
- financeextras.php
- js/addContributionCreditNoteBtn.js
- js/modifyContributionForm.js
- js/modifyMemberForm.js
- js/modifyParticipantForm.js
- templates/CRM/Financeextras/Form/Contribute/AddPayment.tpl
- templates/CRM/Financeextras/Form/Contribute/CustomLineItem.tpl
- templates/CRM/Financeextras/Form/Event/AddContribution.tpl
- templates/CRM/Financeextras/Form/Member/AddPayment.tpl
This PR merges the workstream branch together
> CIWEMB-15: Combine workstream branches

- ang/fe-creditnote/directives/creditnote-allocation-table.directive.html
- ang/fe-creditnote/directives/creditnote-allocation-table.directive.js
- ang/fe-creditnote/directives/creditnote-view.directive.js
- js/modifyMemberForm.js
This PR introduces the following changes
- Update membership Payment amount when contribution amount is updated
- Prevent allocating credit of voided credit note
The membership payment amount is not updated when the contribution amount is updated.
The membership payment amount is updated when the contribution amount is updated.
The allocate credit note button appears on the view of a voided credit note. 
The allocate credit note button doesn't appear on the view of a voided credit note.
> CIWEMB-459: Update membership Payment amount when contribution amount is updated

- css/fe-creditnote.css
- templates/CRM/Financeextras/MessageTemplate/CreditNoteInvoice.tpl
> CIWEMB-517: Update credit note invoice

- financeextras.civix.php
- financeextras.php
- info.xml
- phpunit.xml.dist
- tests/phpunit/BaseHeadlessTest.php
Upgrade Civix version to 22.05.2 using the command `civix upgrade`
> ESEB-53: Upgrade civix to version 22.05.2

- CRM/Financeextras/Form/ExchangeRateSettings.php
- financeextras.php
- templates/CRM/Financeextras/Form/ExchangeRateSettings.hlp
- templates/CRM/Financeextras/Form/ExchangeRateSettings.tpl
- xml/Menu/financeextras.xml
This PR adds the exchange rate settings page
`CiviContribute >> Currency Exchange Settings`
The settings page doesn't exist
> ESEB-67: Add Exchange Rate settings page

- CRM/Financeextras/Form/ExchangeRate/Add.php
- templates/CRM/Financeextras/Form/ExchangeRate/Add.tpl
This PR prevents duplicate exchange rate entry
`no validation exists`
> ESEB-98: Prevent duplicate exchange rate entry

- templates/CRM/Financeextras/Form/Contribute/CreditNoteDelete.tpl
Change the delete confirmation message for credit notes.
> CIWEMB-501: Update Delete Credit Note Message

- info.xml
This pr bumps version to 2.1.1
> COMCL-462: Bump Version To 2.1.1

- Civi/Financeextras/Service/CreditNoteInvoiceService.php
The tax rate displayed on a credit note invoice has the probability of displaying values with round-off errors, for example, 20.00 is displayed as 19.99, this happens because we do not save the tax_rate instead we save the tax amount, so we attempt to compute the tax_rate from the tax_amount, hence the round-off errors.
The solution to this is to use the financial type to get the tax rate.
> MAE-1097: Correct credit note invoice tax rate

- Civi/Financeextras/APIWrapper/SearchDisplayRun.php
- ang/afsearchAllocatedPaymentsReport.aff.html
- ang/afsearchAllocatedPaymentsReport.aff.json
- managed/SavedSearch_SOA_Finance_Report_Beta_v3.mgd.php
Allow users to view and export the Allocated Payments Report
_N/A_
> SA-146: Allow user to export Allocated Payments Report

- Civi/Financeextras/Hook/BuildForm/ContributionCreate.php
- info.xml
This pr bumps the version to 2.1.2 and includes a [contribution form bug fix](https://github.com/compucorp/io.compuco.financeextras/pull/149)
> COMCL-474: Bump Version To 2.1.2

- info.xml
Bump version for 2.1.3 release
> COMCL-471: Bump version for release

- js/modifyMemberForm.js
This pr hides the free or paid memberships radio buttons for free memberships on admin membership creation form.
> CIWEMB-503: Hide Free Or Paid Membership Radio Buttons For Free Memberships

- Civi/Financeextras/Token/CreditNote.php
This PR ensures that credit note tokens are displayed in the message template tokens selector
The credit note tokens are not listed
Tokens are displayed in the selector
Tokens values are resolved appropriately
> PROD-184: Add support for credit note tokens in message template form

- info.xml
> COMCL-523: Bump version for 2.1.5 release

- info.xml
This pr bumps version to 2.1.5+patch1
> COMCL-546: Bump Version

- info.xml
This pr bumps version to 2.1.6
> COMCL-546: Bump Version to 2.1.6

- Civi/Financeextras/Hook/Post/ContributionCreation.php
This pr updates the contribution's payment method snd set it equal to the payment method of the owner organization when a pay later contribution is created
.
> PROD-203: Update Contribution Payment Method

- CRM/Financeextras/Upgrader.php
This pr adds a new upgrader to the extension that would result in updating the default company's account receivable payment method to the default account receivable payment method.
> PROD-205: Update To Default Receivable Account

- Civi/Financeextras/Setup/Configure/SetDefaultCompany.php
This pr uses the default receivable account while creating the default company on the installation of this extension.
> PROD-204: Use Default Receivable Account

- Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php
This pr allows the user to use soft credit while creating the contributions as currently there is a bug that do not allow the usage of soft credit during contribution creation.
Even though the soft credit amount is less than total contribution amount but still the form throws an error
The contribution can be created successfully if the soft credit amount is less than the total contribution amount.
Contribution is unaware of the line items and it cant compute total amount from them so total amount is 0 and when civi compares the soft credit amount with total amount of 0 it throws error that soft credit amount cannot be more than total amount. This pr checks that if the a soft credit field's amount is less than the line item totals than it remove the error for that particular soft credit …
> CIVIPLMMSR-287: Fix Soft Credit Bug On Create Contribution Page

- Civi/Financeextras/Hook/Post/ContributionCreation.php
In this previous PR https://github.com/compucorp/io.compuco.financeextras/pull/178, we update the payment processor for contribution to the default account receivable payment method, if no payment is attached to the contribution during creation.
In this PR, we excluded the contribution with direct debit and offline recurring payment from the process.
> COMCL-594: Exclude direct debit and offline recur payment from having account receivable payment processor

- info.xml
Bump Version for 2.1.7 release
> COMCL-562: Bump Version for 2.1.7 release

- CRM/Financeextras/Upgrader.php
- sql/upgrade_1000.sql
The upgrade process was running the auto install script multiple times which could result in an error for some clients due to the fact that later upgrades tries to make changes again which have already been done as part of auto install script. This pr fixes this issue.
> SA-218: Fix Upgrade Process

- info.xml
Bump version for 2.1.8 release
> COMCL-819: Bump version for 2.1.8 release

- js/modifyMemberForm.js
This PR updates the membership type field when price set is selected
> COMCL-745: Update membershiptype field when priceset is selected

- CRM/Financeextras/BAO/CreditNote.php
- CRM/Financeextras/BAO/CreditNoteLine.php
- ang/fe-creditnote/directives/creditnote-create.directive.js
This pr fixes the rounding issues in credit note amount calculations.
> CSTMM-29: Fix rounding issues in credit note

- CRM/Financeextras/BAO/CreditNoteAllocation.php
Revert PR https://github.com/compucorp/io.compuco.financeextras/pull/202
> CIVIMM-213: Revert PR https://github.com/compucorp/io.compuco.financeextras/pull/202

- info.xml
> COMCL-914: Merge Rc Branch To Master

- info.xml
> COMCL-980: Merge Rc Branch To Master

- templates/CRM/Financeextras/Page/Contribute/CreditNoteAngular.tpl
This pr fixes errors that arised when smarty engine was upgraded to version 4.
> COMCL-954: Add Fixes For Smarty4 Upgrade

- js/modifyParticipantForm.js
This pr fixes an issue with event participation form that restricted the user from updating a participant.
> COMCL-1030: Fix Participant Edition Form

- CRM/Financeextras/Settings.php
- CRM/Financeextras/Upgrader.php
- Civi/Financeextras/Hook/BuildForm/PaymentCreate.php
- Civi/Financeextras/Service/IncompleteContributionFixService.php
- Civi/Financeextras/Setup/Manage/CreditNoteInvoiceTemplateManager.php
- ang/fe-creditnote.ang.php
- css/fe-creditnote.css
- financeextras.php
- info.xml
- js/modifyContributionForm.js
- js/modifyMemberForm.js
- js/modifyParticipantForm.js
- templates/CRM/Financeextras/Page/Contribute/CreditNoteAngular.tpl
- templates/CRM/Financeextras/Page/Contribute/CreditNoteTab.tpl
- tests/phpunit/Civi/Financeextras/Service/IncompleteContributionFixServiceTest.php
- tests/phpunit/Civi/Financeextras/Test/Fabricator/MembershipFabricator.php
- tests/phpunit/Civi/Financeextras/Test/Fabricator/MembershipTypeFabricator.php
This PR bumps the version to 2.4.0
> COMCL-1010: Bump Version

- info.xml
Bump version for 2.4.1 release
> COMCL-1057: Bump version for 2.4.1 release

- CRM/Financeextras/Upgrader.php
We added an upgrader to fix some faulty contributions in [this](https://github.com/compucorp/io.compuco.financeextras/pull/217) PR but later on we found out that this needs a much deeper look so the final solution to fix these fault contributions is still a work in progress so this PR removes this upgrader and a final version of this service and upgrader will be added back in later versions.
> CIVIPLMMSR-462: Remove Unwanted Upgrader

- Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php
This PR is in continuation of https://github.com/compucorp/io.compuco.financeextras/pull/225 and https://github.com/compucorp/io.compuco.financeextras/pull/135 and it corrects the calculation of non deductible amount when a line items are used on contribution screen. As described in above PRs the total amount calculation in core civicrm for line items is not correct and when a financial type that is set to be non deductible is used then civi sets the wrongly calculated total amount as non deductible amount as well. So this PR fixes this issue by setting up correct non deductible amount based on line items as once it is set civi will not recalculate it.
This change will only run if there is no price set selected and non deductible amount is not set at the form level which currently is not …
> COMCL-1077: Fix Non Deductible Amount Calculation

- Civi/Financeextras/Hook/ValidateForm/ContributionCreate.php
- info.xml
This PR merges rc branch to master.
> COMCL-1072: Merge Rc to Master

- info.xml
Bump version for 2.4.5 release
> COMCL-1148: Bump version for 2.4.5 release

- CRM/Financeextras/BAO/CreditNoteAllocation.php
- CRM/Financeextras/Page/AJAX.php
This PR alters the transaction records that are created when allocating a credit note to an invoice.
Currently we only create one financial transactions with positive amount and attach it to contribution and allocation as well.
Now we are going to create a new financial transaction with negative amount which will be attached to allocation only to balance out the first transaction during the exporting of batches.
This new transaction will be created as follows
```
"from_financial_account_id": "Accounts Receivable account for the financial type of the first line of the credit note.",
"to_financial_account_id": "Accounts Receivable account for the financial type of the first line of the credit note.",
"trxn_date": "date of the allocation",
"total_amount": "amount allocated (negative)", …
```
> CIVIMM-381: Fix Allocation Transactions
